apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  USERNAME:  SECRET_USERNAME    
  PASSWORD:  SECRET_PASSWORD
---
apiVersion: v1
kind: Pod
metadata:
  name: app-secret-env
spec:
  containers:
    - name: app
      image: nginx:latest
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: PASSWORD
