apiVersion: v1
kind: Pod
metadata:
  name: http-response-readiness
spec:
  containers:
  - name: http-response
    image: ghcr.io/itopsandrii/http_responce:2.0.0
    ports:
    - containerPort: 8000
    readinessProbe:
      httpGet:
        path: /
        port: 8000
      periodSeconds: 2
      initialDelaySeconds: 0
      failureThreshold: 3
      successThreshold: 1