apiVersion: batch/v1
kind: CronJob
metadata:
  name: bash-test-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: bash
              image: bash
              command: ["bash", "-c", "echo Running test; sleep 10"]
          restartPolicy: OnFailure
