apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-app
spec:
  containers:
    - name: app
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: sidecar
      image: busybox
      command: ["sh", "-c", "while true; do echo Sidecar running; sleep 60; done"]
