apiVersion: v1
kind: Pod
metadata:
  name: http-response
  labels:
    app: http
spec:
  containers:
  - name: http-response
    image: ghcr.io/itopsandrii/http_responce:2.0.0
    ports:
    - containerPort: 8000

